### ISSUE TITLE
missing stream exception

### ISSUE THREAD

**Issue by primaeval** [vonH/plugin.video.iplayerwww#12]
I got this connection error from Scream Street this morning:
```
07:20:19 T:5424   ERROR: XFILE::CDirectory::GetDirectory - Error getting plugin://plugin.video.iplayerwww/?description=Eefa%27s%20magic%20cleaning%20powder%20bring%27s%20Luke%27s%20vacuum%20cleaner%20to%20life.&iconimage=http%3a%2f%2fichef.bbci.co.uk%2fimages%2fic%2f406x228%2fp0350p0h.jpg&mode=122&name=Scream%20Street%3a%201.%20Scream%20Clean&subtitles_url&url=http%3a%2f%2fwww.bbc.co.uk%2fiplayer%2fepisode%2fb06kvync
07:20:19 T:5424   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.iplayerwww/?description=Eefa%27s%20magic%20cleaning%20powder%20bring%27s%20Luke%27s%20vacuum%20cleaner%20to%20life.&iconimage=http%3a%2f%2fichef.bbci.co.uk%2fimages%2fic%2f406x228%2fp0350p0h.jpg&mode=122&name=Scream%20Street%3a%201.%20Scream%20Clean&subtitles_url&url=http%3a%2f%2fwww.bbc.co.uk%2fiplayer%2fepisode%2fb06kvync) failed
07:20:19 T:5012  NOTICE: Thread LanguageInvoker start, auto delete: false
07:20:19 T:5012  NOTICE: -->Python Interpreter Initialized<--
07:20:23 T:3564   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <class 'requests.exceptions.ConnectionError'>
                                            Error Contents: ('Connection aborted.', error(10060, 'A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond'))
                                            Traceback (most recent call last):
                                              File "C:\Kodi15.1\portable_data\addons\plugin.video.iplayerwww-1.1.2\default.py", line 1050, in <module>
                                                GetAvailableStreams(name, url, iconimage, description)
                                              File "C:\Kodi15.1\portable_data\addons\plugin.video.iplayerwww-1.1.2\default.py", line 694, in GetAvailableStreams
                                                AddAvailableStreamsDirectory(name, stream_ids['stream_id_st'], iconimage, description)
                                              File "C:\Kodi15.1\portable_data\addons\plugin.video.iplayerwww-1.1.2\default.py", line 491, in AddAvailableStreamsDirectory
                                                streams = ParseStreams(stream_id)
                                              File "C:\Kodi15.1\portable_data\addons\plugin.video.iplayerwww-1.1.2\default.py", line 520, in ParseStreams
                                                html = OpenURL(NEW_URL)
                                              File "C:\Kodi15.1\portable_data\addons\plugin.video.iplayerwww-1.1.2\default.py", line 784, in OpenURL
                                                r = requests.get(url, headers=headers)
                                              File "C:\Kodi15.1\portable_data\addons\script.module.requests\lib\requests\api.py", line 69, in get
                                                return request('get', url, params=params, **kwargs)
                                              File "C:\Kodi15.1\portable_data\addons\script.module.requests\lib\requests\api.py", line 50, in request
                                                response = session.request(method=method, url=url, **kwargs)
                                              File "C:\Kodi15.1\portable_data\addons\script.module.requests\lib\requests\sessions.py", line 465, in request
                                                resp = self.send(prep, **send_kwargs)
                                              File "C:\Kodi15.1\portable_data\addons\script.module.requests\lib\requests\sessions.py", line 573, in send
                                                r = adapter.send(request, **kwargs)
                                              File "C:\Kodi15.1\portable_data\addons\script.module.requests\lib\requests\adapters.py", line 415, in send
                                                raise ConnectionError(err, request=request)
                                            ConnectionError: ('Connection aborted.', error(10060, 'A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond'))
                                            -->End of Python script error report<--
07:20:23 T:5424   ERROR: XFILE::CDirectory::GetDirectory - Error getting plugin://plugin.video.iplayerwww/?description&iconimage&mode=106&name=Highlights&subtitles_url&url=url
07:20:23 T:5424   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.iplayerwww/?description&iconimage&mode=106&name=Highlights&subtitles_url&url=url) failed
```

**Comment by primaeval** [comment]
My fix:
https://github.com/primaeval/plugin.video.iplayerwww/commit/3743ce345ff57e227e2a65cdb4b2680bab432424

**Comment by CaptainTK** [comment]
This is simply a timeout error. I can access the episode just fine. However, I will create an issue to improve this behaviour in general.
