### ISSUE TITLE
Python errors in log - Error getting plugin

### ISSUE THREAD

**Issue by iparr** [vonH/plugin.video.iplayerwww#22]
I've installed this fresh today from the repo and have disabled all other iPlayer-related plugins.

```
18:10:18 T:140275309606656  NOTICE: Previous line repeats 1 times.
18:10:18 T:140275309606656  NOTICE: Thread BackgroundLoader start, auto delete: false
18:10:23 T:140275309606656  NOTICE: Previous line repeats 1 times.
18:10:23 T:140275309606656  NOTICE: Thread JobWorker start, auto delete: true
18:10:26 T:140275301213952  NOTICE: Thread BackgroundLoader start, auto delete: false
18:10:43 T:140275301213952  NOTICE: Previous line repeats 1 times.
18:10:43 T:140275301213952  NOTICE: Thread LanguageInvoker start, auto delete: false
18:10:43 T:140275301213952  NOTICE: -->Python Interpreter Initialized<--
18:10:43 T:140275301213952   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.RuntimeError'>
                                            Error Contents: osrandom engine already registered
                                            Traceback (most recent call last):
                                              File "/home/pr0/.kodi/addons/plugin.video.iplayerwww/default.py", line 13, in <module>
                                                import requests
                                              File "/home/pr0/.kodi/addons/script.module.requests/lib/requests/__init__.py", line 53, in <module>
                                                from .packages.urllib3.contrib import pyopenssl
                                              File "/home/pr0/.kodi/addons/script.module.requests/lib/requests/packages/urllib3/contrib/pyopenssl.py", line 53, in <module>
                                                import OpenSSL.SSL
                                              File "/usr/local/lib/python2.7/dist-packages/OpenSSL/__init__.py", line 8, in <module>
                                                from OpenSSL import rand, crypto, SSL
                                              File "/usr/local/lib/python2.7/dist-packages/OpenSSL/rand.py", line 11, in <module>
                                                from OpenSSL._util import (
                                              File "/usr/local/lib/python2.7/dist-packages/OpenSSL/_util.py", line 7, in <module>
                                                binding = Binding()
                                              File "/usr/local/lib/python2.7/dist-packages/cryptography/hazmat/bindings/openssl/binding.py", line 63, in __init__
                                                self._ensure_ffi_initialized()
                                              File "/usr/local/lib/python2.7/dist-packages/cryptography/hazmat/bindings/openssl/binding.py", line 95, in _ensure_ffi_initialized
                                                cls._register_osrandom_engine()
                                              File "/usr/local/lib/python2.7/dist-packages/cryptography/hazmat/bindings/openssl/binding.py", line 70, in _register_osrandom_engine
                                                raise RuntimeError("osrandom engine already registered")
                                            RuntimeError: osrandom engine already registered
                                            -->End of Python script error report<--
18:10:18 T:140275309606656  NOTICE: Thread BackgroundLoader start, auto delete: false
18:10:23 T:140275309606656  NOTICE: Previous line repeats 1 times.
18:10:23 T:140275309606656  NOTICE: Thread JobWorker start, auto delete: true
18:10:26 T:140275301213952  NOTICE: Thread BackgroundLoader start, auto delete: false
18:10:43 T:140275301213952  NOTICE: Previous line repeats 1 times.
18:10:43 T:140275301213952  NOTICE: Thread LanguageInvoker start, auto delete: false
18:10:43 T:140275301213952  NOTICE: -->Python Interpreter Initialized<--
18:10:43 T:140275301213952   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.RuntimeError'>
                                            Error Contents: osrandom engine already registered
                                            Traceback (most recent call last):
                                              File "/home/pr0/.kodi/addons/plugin.video.iplayerwww/default.py", line 13, in <module>
                                                import requests
                                              File "/home/pr0/.kodi/addons/script.module.requests/lib/requests/__init__.py", line 53, in <module>
                                                from .packages.urllib3.contrib import pyopenssl
                                              File "/home/pr0/.kodi/addons/script.module.requests/lib/requests/packages/urllib3/contrib/pyopenssl.py", line 53, in <module>
                                                import OpenSSL.SSL
                                              File "/usr/local/lib/python2.7/dist-packages/OpenSSL/__init__.py", line 8, in <module>
                                                from OpenSSL import rand, crypto, SSL
                                              File "/usr/local/lib/python2.7/dist-packages/OpenSSL/rand.py", line 11, in <module>
                                                from OpenSSL._util import (
                                              File "/usr/local/lib/python2.7/dist-packages/OpenSSL/_util.py", line 7, in <module>
                                                binding = Binding()
                                              File "/usr/local/lib/python2.7/dist-packages/cryptography/hazmat/bindings/openssl/binding.py", line 63, in __init__
                                                self._ensure_ffi_initialized()
                                              File "/usr/local/lib/python2.7/dist-packages/cryptography/hazmat/bindings/openssl/binding.py", line 95, in _ensure_ffi_initialized
                                                cls._register_osrandom_engine()
                                              File "/usr/local/lib/python2.7/dist-packages/cryptography/hazmat/bindings/openssl/binding.py", line 70, in _register_osrandom_engine
                                                raise RuntimeError("osrandom engine already registered")
                                            RuntimeError: osrandom engine already registered
                                            -->End of Python script error report<--
18:10:43 T:140277107791808   ERROR: GetDirectory - Error getting plugin://plugin.video.iplayerwww/
18:10:43 T:140277107791808   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.iplayerwww/) failed
18:10:43 T:140275301213952  NOTICE: Thread BackgroundLoader start, auto delete: false
```

I'm on a Ubuntu Linux machine, with Kodi 15.2 installed.

**Comment by CaptainTK** [comment]
Thanks for reporting this problem.

However, it seems unrelated to iPlayer WWW. The error is raised during the import of another add-on which iPlayer WWW relies on: Python requests (see http://addons.kodi.tv/show/script.module.requests/). There seems to be some sort of conflict between Python requests and osrandom, yet another Python module.

So this problem seems to be related to Python requests in your configuration, not to iPlayer WWW.

**Comment by iparr** [comment]
Resolving problems with some other services as reference above fixed this and the plugin is now working well.

Thanks for the pointer, @CaptainTK
