### ISSUE TITLE
playing programme fails:  'NoneType' object has no attribute 'encode'

### ISSUE THREAD

**Issue by oschonrock** [vonH/plugin.video.iplayerwww#241]
V3.0.25 under Kodi 17.6 & OSMC 2018.04-2
Watching live TV works fine  (so should not be BBC ID related, or network related)
Starting any past programme from Programme A-Z list fails with following exception in kodi.log
Error started occurring on May 22th, 2018 after working flawlessly for years. 

```
ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
- NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
Error Type: <type 'exceptions.AttributeError'>
Error Contents: 'NoneType' object has no attribute 'encode'
Traceback (most recent call last):
File "/home/osmc/.kodi/addons/plugin.video.iplayerwww/default.py", line 167, in <module>
Video.GetEpisodes(url)
File "/home/osmc/.kodi/addons/plugin.video.iplayerwww/resources/lib/ipwww_video.py", line 256, in GetEpisodes
ScrapeEpisodes(new_url)
File "/home/osmc/.kodi/addons/plugin.video.iplayerwww/resources/lib/ipwww_video.py", line 511, in ScrapeEpisodes
CheckAutoplay(title , main_url, icon, synopsis, aired)
File "/home/osmc/.kodi/addons/plugin.video.iplayerwww/resources/lib/ipwww_video.py", line 1945, in CheckAutoplay
AddMenuEntry(name, url, 202, iconimage, plot, '', aired=aired)
File "/home/osmc/.kodi/addons/plugin.video.iplayerwww/resources/lib/ipwww_common.py", line 328, in AddMenuEntry
"&logged_in=" + str(logged_in))
File "/home/osmc/.kodi/addons/plugin.video.iplayerwww/resources/lib/ipwww_common.py", line 308, in utf8_quote_plus
return urllib.quote_plus(unicode.encode('utf-8'))
AttributeError: 'NoneType' object has no attribute 'encode'

```

**Comment by oschonrock** [comment]
this one liner fixes it:

```
diff -bu ipwww_video_orig.py ipwww_video.py
--- ipwww_video_orig.py	2018-05-23 19:04:22.793715911 +0100
+++ ipwww_video.py	2018-05-23 20:25:59.094642480 +0100
@@ -481,6 +481,7 @@
 
             for item in json_data['initialState']['entities']:
 
+                item = item['props']
                 main_url = None
                 if 'href' in item:
                     # Some strings already contain the full URL, need to work around this.

```
redefining "item" is probably not great style, so a different patch is probably appropriate.

Basically the problem appears to be that there is an additional wrapping "props" key in the json  received from bbciplayer.

make sense?

**Comment by oschonrock** [comment]
This would also fix it:
https://github.com/vonH/plugin.video.iplayerwww/commit/99897567b6b9dc559d207633089d3ff19a8d2f76
Therefore fixed on master just needs tag & release
Closing this here.
