### ISSUE TITLE
Plugin says I'm not in the UK

### ISSUE THREAD

**Issue by springjools** [vonH/plugin.video.iplayerwww#324]
Plugin says I'm not in the UK, but I am. I get the following error in logs when trying to play any item:

2020-05-17 00:27:01.255 T:2287984960   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.KeyError'>
                                            Error Contents: 'keyword'
                                            Traceback (most recent call last):
                                              File "/home/kodi/.kodi/addons/plugin.video.iplayerwww/default.py", line 222, in <module>
                                                Video.AddAvailableLiveStreamItemSelector(name, url, iconimage)
                                              File "/home/kodi/.kodi/addons/plugin.video.iplayerwww/resources/lib/ipwww_video.py", line 856, in AddAvailableLiveStreamItemSelector
                                                return AddAvailableLiveStreamItem(name, channelname, iconimage)
                                              File "/home/kodi/.kodi/addons/plugin.video.iplayerwww/resources/lib/ipwww_video.py", line 916, in AddAvailableLiveStreamItem
                                                PlayStream(name, streams_available[0][4], iconimage, '', '')
                                              File "/home/kodi/.kodi/addons/plugin.video.iplayerwww/default.py", line 93, in <module>
                                                keyword = utf8_unquote_plus(params["keyword"])
                                            KeyError: 'keyword'
                                            -->End of Python script error report<--
2020-05-17 00:27:01.453 T:2984729088   ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.iplayerwww/?url=bbc_two_hd&mode=203&name=BBC+Two&iconimage=%2Fhome%2Fkodi%2F.kodi%2Faddons%2Fplugin.video.iplayerwww%2Fmedia%2Fbbc_two_hd.png&description=&subtitles_url=&logged_in=False&time=1589664402.01]

Using Kodi 18.6 on debian 10 (buster)

**Comment by CaptainTK** [comment]
When do you get this error?
Only for BBC 2 live?
For all live channels?
Also for catch-up?
What are your stream settings? DASH? HLS? Autoplay in or off (looks like off)?
Are you logged in?
Does the error change when logged in vs. not being logged in?

**Comment by DoctorOctagonapus** [comment]
I get the same error streaming BBC1. I'm here in the UK but it thinks I'm abroad. Here's the error from my kodi.log

`2021-05-22 20:05:50.437 T:1193304944   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.KeyError'>
                                            Error Contents: 'keyword'
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.video.iplayerwww/default.py", line 222, in <module>
                                                Video.AddAvailableLiveStreamItemSelector(name, url, iconimage)
                                              File "/storage/.kodi/addons/plugin.video.iplayerwww/resources/lib/ipwww_video.py", line 880, in AddAvailableLiveStreamItemSelector
                                                return AddAvailableLiveStreamItem(name, channelname, iconimage)
                                              File "/storage/.kodi/addons/plugin.video.iplayerwww/resources/lib/ipwww_video.py", line 940, in AddAvailableLiveStreamItem
                                                PlayStream(name, streams_available[0][4], iconimage, '', '')
                                              File "/storage/.kodi/addons/plugin.video.iplayerwww/default.py", line 93, in <module>
                                                keyword = utf8_unquote_plus(params["keyword"])
                                            KeyError: 'keyword'
                                            -->End of Python script error report<--
2021-05-22 20:05:50.534 T:3011228256   ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.iplayerwww/?url=bbc_one_hd&mode=203&name=BBC+One&iconimage=%2Fstorage%2F.kodi%2Faddons%2Fplugin.video.iplayerwww%2Fmedia%2Fbbc_one_hd.png&description=&subtitles_url=&logged_in=False&time=1621710346.48]`

Signing into BBC ID makes no difference.

**Comment by CaptainTK** [comment]
Most likely you are experiencing an issue in inputstream adaptive that has been fixed a while ago.

Which version of
* Kodi
* plugin.Video.iplayerwww
* Inputstream Adaptive
are you using?

Also, please disable autoplay in the add-on settings to check if the issue is related to a certain CDN.

**Comment by DoctorOctagonapus** [comment]
Ah updating iPlayer from 3.0.49 to 3.0.50 got it working. Inputstream I'm on 2.4.6.1 and Kodi is 9.2.6 on LibreELEC.
