### ISSUE TITLE
Unable to play Battlestar Galactica S1 first 3 episodes

### ISSUE THREAD

**Issue by Sonosy** [vonH/plugin.video.iplayerwww#330]
Everything else plays OK and the episodes are available on get_iplayer

Error log for first unplayable episode
```
2020-09-07 09:50:44.461 T:1233105120   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.IndexError'>
                                            Error Contents: list index out of range
                                            Traceback (most recent call last):
                                              File "/home/kodi/.kodi/addons/plugin.video.iplayerwww/default.py", line 219, in <module>
                                                Video.AddAvailableStreamItem(name, url, iconimage, description)
                                              File "/home/kodi/.kodi/addons/plugin.video.iplayerwww/resources/lib/ipwww_video.py", line 814, in AddAvailableStreamItem
                                                PlayStream(name, match[0][2], iconimage, description, subtitles_url)
                                            IndexError: list index out of range
                                            -->End of Python script error report<--
2020-09-07 09:50:44.639 T:1900172208   ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.iplayerwww/?url=https%3A%2F%2Fwww.bbc.co.uk%2Fiplayer%2Fepisode%2Fp08l2n7q%2Fbattlestar-galactica-series-1-1-mini-series-part-1&mode=202&name=1.+Mini+Series+-+Part+1+-+Galactica+is+once+again+drawn+into+conflict+after+a+shock+attack+on+the+12+Colonies.&iconimage=https%3A%2F%2Fichef.bbci.co.uk%2Fimages%2Fic%2F832x468%2Fp08mv83l.jpg&description=Galactica+is+once+again+drawn+into+conflict+after+a+shock+attack+on+the+12+Colonies.&subtitles_url=&logged_in=False]

```

**Comment by CaptainTK** [comment]
I am afraid, this time it is not the add-on's fault. For these programmes, the Beeb serve an empty mediaselector response. Well, it is not entirely empty, it still contains the subtitles, but no useful streams. It works fine when using the PC mediaselector in a browser. So either there is a configuration error on the Beeb's side, or they are phasing out the mediaselector we use.

get_iplayer uses a different access, I did not have a chance to look at it in detail lately. If I recall correctly, they are using fake IDs to connect to the Nitro API. This is something I would not want to implement in the add-on, as it is dubious at best.

Personally, I expect this problem to resolve itself within a couple of days. If it does not, I will look into it further.

**Comment by Sonosy** [comment]
Thanks @CaptainTK for a quick response

I get the gist of your explanation.
Maybe next time you're in that code it could be a bit more graceful/informative?
Maybe catch the index out of range error and pop up a "Beeb error - no streams available" message?
Thanks to all for a great plugin.
I'll close this to keep things tidy :-)
