### ISSUE TITLE
Error on fresh install caused by setting which no longer exist

### ISSUE THREAD

**Issue by sunjaxx** [vonH/plugin.video.iplayerwww#343]
I just installed kodi 19 on android tv (nvidia Shield) and tried this 4.0 beta add-on, but it won't open. the log shows the following. Any ideas?

2021-02-28 13:46:50.090 T:8056     INFO <general>: Loading skin file: MyVideoNav.xml, load type: KEEP_IN_MEMORY
2021-02-28 13:46:50.194 T:8953     INFO <general>: initializing python engine.
2021-02-28 13:46:50.869 T:8953  WARNING <CAddonSettings[plugin.video.iplayerwww]>: cannot reference separator setting in old setting condition "eq(-4,true) " for "catchup_bitrate"
2021-02-28 13:46:50.869 T:8953  WARNING <CAddonSettings[plugin.video.iplayerwww]>: cannot reference separator setting in old setting condition " eq(-2,1)" for "catchup_bitrate"
2021-02-28 13:46:50.869 T:8953  WARNING <CAddonSettings[plugin.video.iplayerwww]>: failed to parse enable condition "eq(-4,true) + eq(-2,1)" of old setting definition for "catchup_bitrate"
2021-02-28 13:46:50.869 T:8953  WARNING <CAddonSettings[plugin.video.iplayerwww]>: cannot reference separator setting in old setting condition "eq(-5,true)" for "live_source"
2021-02-28 13:46:50.869 T:8953  WARNING <CAddonSettings[plugin.video.iplayerwww]>: failed to parse enable condition "eq(-5,true)" of old setting definition for "live_source"
2021-02-28 13:46:50.869 T:8953  WARNING <CAddonSettings[plugin.video.iplayerwww]>: cannot reference separator setting in old setting condition "eq(-6,true) " for "live_bitrate"
2021-02-28 13:46:50.869 T:8953  WARNING <CAddonSettings[plugin.video.iplayerwww]>: cannot reference separator setting in old setting condition " eq(-4,1)" for "live_bitrate"
2021-02-28 13:46:50.869 T:8953  WARNING <CAddonSettings[plugin.video.iplayerwww]>: failed to parse enable condition "eq(-6,true) + eq(-4,1)" of old setting definition for "live_bitrate"
2021-02-28 13:46:50.927 T:8953    ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'ValueError'>
                                                   Error Contents: invalid literal for int() with base 10: ''
                                                   Traceback (most recent call last):
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.iplayerwww/default.py", line 102, in <module>
                                                       CreateBaseDirectory(content_type)
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.iplayerwww/resources/lib/ipwww_common.py", line 626, in CreateBaseDirectory
                                                       AddMenuEntry(translation(30325), 'url', 119,
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.iplayerwww/resources/lib/ipwww_common.py", line 468, in AddMenuEntry
                                                       if int(ADDON.getSetting('stream_protocol')) == 0:
                                                   ValueError: invalid literal for int() with base 10: ''
                                                   -->End of Python script error report<--
                                                   
2021-02-28 13:46:51.066 T:8953     INFO <general>: Python interpreter stopped
2021-02-28 13:46:51.080 T:8951    ERROR <general>: GetDirectory - Error getting plugin://plugin.video.iplayerwww/?content_type=video
2021-02-28 13:46:51.087 T:8056    ERROR <general>: CGUIMediaWindow::GetDirectory(plugin://plugin.video.iplayerwww/?content_type=video) failed

**Comment by CaptainTK** [comment]
This should do the trick. Please reopen if it does not.

**Comment by sunjaxx** [comment]
It did, thanks!
